---
# tasks file for install-ansible
- name: Install python3, pip3
  become: yes
  become_user: 'root'
  yum:
    name:
      - python3
      - python3-pip

- name: Install ansible, boto, boto3 via pip3
  pip:
    name:
      - ansible
      - boto
      - boto3
    executable: pip3
    extra_args: "--user"

- name: Create ansible.log file
  file:
    path: /var/log/ansible.log
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    state: touch
  vars:
    ansible_become_user: root
  tags: ['logs']